### ISSUE TITLE
Does each image-text pair in the training dataset used in the paper contain descriptions for all four modalities?

### ISSUE THREAD

**Issue by Xqq2620xx** [ljy19970415/UniBrain#1]
Thank you for your contribution, excellent work! I have a question I'd like to confirm.

Does each image-text pair in the training dataset used in the paper contain descriptions for all four modalities (T1WI, T2WI, T2FLAIR, DWI)? If for some samples, one modality is missing, how was this handled during training?

**Comment by ljy19970415** [comment]
Hi, thanks for paying attention to our work. Before answering your question, one thing should be clear is that each training data (imaging-report pair) can be regarded as a patient.
You question can be answered from two aspects:
1. A training data/imaging-report pair/patient lacks images for specific modalities.
This will not happen because each patient will take MRI imagings of four modalities (T1WI, T2WI, T2FLAIR, DWI).
2. Report in a training data/imaging-report pair/patient lacks descriptions for specific modalities.
Our modal-wise report contains two parts: signal intensity and morphological changes. 
2.1 Signal intensity
Doctors don't always describe signal intensity for all modalities in one report. If signal intensity isn't mentioned for one modality, we will then check the morphological changes.  If signal intensity is mentioned for one modality, we will first add the signal intensity to the modal-wise report and then check the morphological changes. 
2.2 Morphological changes.
If the brain is abnormal, doctors will always mention morphological changes, such as enlarged sulcis. The morphological changes is common in all modalities. So once we see descriptions about morphological changes, we will add it to each modal-wise report. In most cases, this will avoid the emptyness of our modal-wise report since descriptions about morphological changes is really common in reports.
2.3 Otherwise
Situations about neither signal intensity nor morphological changes descriptions exist are rare. If it happens, the report will be 'unspecified'. During the contrastive learning, when two reports are all 'unspecified', they won't be regarded as same reports.

**Comment by Xqq2620xx** [comment]
Sorry, one more thing, in the event of scenario 2.3, when conducting contrastive learning, if the report is missing, do we directly align a blank string and the image?

**Comment by ljy19970415** [comment]
Sorry for the delay reply.
The report contains report observation and report summary.
During our final implementation, the report summary will be added to modalwise report. So the modalwise report will never empty.

**Comment by Katarsisl** [comment]
Hey, how can I get the `'xmcmic/Med-KEBERT'`😁

**Comment by ljy19970415** [comment]
I think it can be downloaded online when you run your code. You can reference the code getting the text encoder at line 402,406 in train.py of [https://github.com/ljy19970415/UniBrain/blob/main/train](url). The config['text_encoder'] can be replaced with 'xmcmic/Med-KEBERT'. Then it should be downloaded online when you run the code.
 If you want to download it on your own, you can get it from [https://huggingface.co/xmcmic/Med-KEBERT/tree/main](url) and store it at a local path. Then you can just replace the config['text_encoder'] with your local path.

**Comment by Katarsisl** [comment]
Thank you for your very timely reply. I used the same method as your train.py at the beginning, but I got the following error:

```
raise ("Invalid model name. Check the config file and pass a BERT model from transformers lybrary")`
```

So I downloaded it manually. Thank you.
